// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZFbM_X9IAbv1E7zXg3qo6xPU4Ar_4pM',
    appId: '1:465481303579:web:2ed7d94b2a14c98cb69abe',
    messagingSenderId: '465481303579',
    projectId: 'healthcolonquest-dddc1',
    authDomain: 'healthcolonquest-dddc1.firebaseapp.com',
    storageBucket: 'healthcolonquest-dddc1.appspot.com',
    measurementId: 'G-XPZ909PXWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDVYrWNP4K8OxYt-QtVCRaS3aaJOzpAs',
    appId: '1:465481303579:android:fecd27fbde2b03c5b69abe',
    messagingSenderId: '465481303579',
    projectId: 'healthcolonquest-dddc1',
    storageBucket: 'healthcolonquest-dddc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnBQVLHU-NsKZkfTxdt_2xjvMc3FhBp4',
    appId: '1:465481303579:ios:e24db2c095a026ebb69abe',
    messagingSenderId: '465481303579',
    projectId: 'healthcolonquest-dddc1',
    storageBucket: 'healthcolonquest-dddc1.appspot.com',
    iosBundleId: 'com.example.hcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnBQVLHU-NsKZkfTxdt_2xjvMc3FhBp4',
    appId: '1:465481303579:ios:e24db2c095a026ebb69abe',
    messagingSenderId: '465481303579',
    projectId: 'healthcolonquest-dddc1',
    storageBucket: 'healthcolonquest-dddc1.appspot.com',
    iosBundleId: 'com.example.hcq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJZFbM_X9IAbv1E7zXg3qo6xPU4Ar_4pM',
    appId: '1:465481303579:web:87047ad85a05c3b9b69abe',
    messagingSenderId: '465481303579',
    projectId: 'healthcolonquest-dddc1',
    authDomain: 'healthcolonquest-dddc1.firebaseapp.com',
    storageBucket: 'healthcolonquest-dddc1.appspot.com',
    measurementId: 'G-E86VG4HQ1T',
  );

}